### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by marcelo321** [synacktiv/eos#12]
Anyone knows how to fix this error?

```
[+] Info
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/root/.local/lib/python3.8/site-packages/eos/utils/log.py", line 65, in format
    s = super().format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
  File "/usr/lib/python3.8/distutils/version.py", line 324, in __str__
    return self.vstring
AttributeError: 'Version' object has no attribute 'vstring'
Call stack:
  File "/usr/local/bin/eos", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/eos/__main__.py", line 197, in main
    args.handler(args)
  File "/root/.local/lib/python3.8/site-packages/eos/__main__.py", line 47, in scan
    eos.run(threads=args.threads)
  File "/root/.local/lib/python3.8/site-packages/eos/core/eos.py", line 72, in run
    manager.run()
  File "/root/.local/lib/python3.8/site-packages/eos/plugins/__init__.py", line 158, in run
    plugin.run()
  File "/root/.local/lib/python3.8/site-packages/eos/plugins/info.py", line 52, in run
    self.log.warning('  Symfony %s', self.symfony.version)
```

**Comment by aevy-syn** [comment]
I cannot reproduce this issue from a fresh Python3.8 installation. Could you please provide more details such as the exact version of the involved components ?
