### ISSUE TITLE
Which Python3 version please?

### ISSUE THREAD

**Issue by bus7d** [synacktiv/eos#6]
Hello tryin to execute the tool , I get this error:

`➜  eos git:(master) ✗ eos             
Traceback (most recent call last):
  File "/usr/local/bin/eos", line 11, in <module>
    load_entry_point('eos==1.1', 'console_scripts', 'eos')()
  File "/usr/local/lib/python3.6/dist-packages/eos-1.1-py3.6.egg/eos/__main__.py", line 123, in main
    sub = p.add_subparsers(dest='command', required=True)
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

it seems to be related to python3 version, I m using 3.6.9 here.

Thank you for the great tool anyway !
`

**Comment by aevy-syn** [comment]
Hi, thank you for your feedback.
EOS has been developed for Python 3.7 and later. We added a note in the README.
