### ISSUE TITLE
Error: 'NoneType' object has no attribute 'find_previous'

### ISSUE THREAD

**Issue by monixxxx** [synacktiv/eos#9]
[x] Could not find phpinfo!

[+] Project files plugin requires Symfony >= 3.0.0

[+] Routes
[x] 'NoneType' object has no attribute 'find_previous'
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/eos/plugins/__init__.py", line 158, in run
    plugin.run()
  File "/root/.local/lib/python3.8/site-packages/eos/plugins/routes.py", line 68, in run
    route = label.find_previous('span', class_='value').text
AttributeError: 'NoneType' object has no attribute 'find_previous'

[+] Project sources plugin requires Symfony >= 3.0.0

**Comment by aevy-syn** [comment]
Hello,
Which Symfony version are trying to run the tool on please ?

**Comment by aevy-syn** [comment]
Duplicate #10
